version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      # Group patch updates together
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      # Group minor updates for common dependencies
      tokio-updates:
        patterns:
          - "tokio*"
        update-types:
          - "minor"
      serde-updates:
        patterns:
          - "serde*"
        update-types:
          - "minor"
    # Allow Dependabot to update lockfile-only changes
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Ignore major version updates for stability
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
