# Rustfmt configuration
# See all options at: https://rust-lang.github.io/rustfmt/

# Enable unstable features
unstable_features = true

# Basic formatting
max_width = 120
tab_spaces = 2
edition = "2024"
newline_style = "Unix"

# Imports formatting
reorder_imports = true
reorder_modules = true
imports_granularity = "Module"  # Merges imports from the same module
group_imports = "StdExternalCrate"  # Groups imports by std, external crates, and local imports
imports_indent = "Block"  # Indent imports with block indentation

# Documentation and comments
format_code_in_doc_comments = true  # Format code snippets in doc comments
wrap_comments = true  # Wrap comments to fit within max_width
normalize_comments = true  # Normalize comments

# Control flow
match_block_trailing_comma = false
