name: Feature Request
description: Suggest an idea that would make Twig better
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Thoughtful proposals help us understand the problem, the desired outcome, and how it fits the roadmap.

  - type: checkboxes
    id: confirmations
    attributes:
      label: Before submitting
      description: Help us focus by confirming the following.
      options:
        - label: I searched existing issues/discussions to avoid duplicates.
          required: true
        - label: I reviewed the docs and CONTRIBUTING guide to confirm this feature does not already exist.
          required: true

  - type: dropdown
    id: area
    attributes:
      label: Area of the project
      description: Where does this feature belong?
      multiple: true
      options:
        - Core CLI (commands, UX)
        - Git integration
        - GitHub integration
        - Jira integration
        - Plugins / plugin API
        - Documentation or tutorials
        - Build / packaging / release
        - Other (explain below)
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem or pain point are you trying to solve? Focus on the user experience.
      placeholder: "When I try to ..., I run into ..."
    validations:
      required: true

  - type: textarea
    id: audience
    attributes:
      label: Who benefits?
      description: Describe who would use this feature (you, your team, plugin authors, etc.).
      placeholder: "This helps ..."
    validations:
      required: true

  - type: textarea
    id: goals
    attributes:
      label: Desired Outcomes / Success Criteria
      description: What does success look like? List concrete goals, acceptance criteria, or user stories.
      placeholder: |
        - Users can ...
        - CLI shows ...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the approach you'd like to see. Include command syntax, config changes, or API sketches if relevant.
      placeholder: |
        Possible CLI syntax:
        ```
        twig <subcommand> --flag
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives or Workarounds
      description: Have you tried other approaches? Why are they insufficient?
      placeholder: "I've also considered ..."

  - type: textarea
    id: considerations
    attributes:
      label: Risks, Dependencies, or Open Questions
      description: Call out potential challenges, interactions with other features, or unknowns.
      placeholder: "We should be careful about ..."

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Include references, related issues, screenshots, or anything else we should review.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct.
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true
