# This section defines the default nextest profile. Custom profiles are layered
# on top of the default profile.
[profile.default]

# Cancel the test run on the first failure. For CI runs, consider setting this
# to false.
# Accepted values are
# * true: cancel the test run on the first failure
# * false: continue running tests even after a failure
# * { max-fail = 10 }: cancel the test run after the specified number of failures
# * { max-fail = "all" }: continue running tests even after a failure
fail-fast = false
