name: Generate Documentation

on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"  # Don't trigger on doc changes
      - "*.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "*.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  generate-docs:
    name: Generate Documentation
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Generate API docs
        run: cargo doc --no-deps --document-private-items

      - name: Generate CLI help docs
        run: |
          cargo build --release
          mkdir -p docs/cli
          ./target/release/twig --help > docs/cli/help.txt
          # Generate help for subcommands
          ./target/release/twig branch --help > docs/cli/branch-help.txt
          ./target/release/twig cascade --help > docs/cli/cascade-help.txt
          ./target/release/twig tree --help > docs/cli/tree-help.txt

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit documentation
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/
          git commit -m "docs: auto-update documentation [skip ci]"
          git push

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: twig-docs
          path: docs/
