name: Generate Documentation

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  generate-docs:
    name: Generate Documentation
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Generate API docs
        run: cargo doc --workspace --no-deps --document-private-items

      - name: Generate unified CLI docs
        run: |
          cargo build --release
          mkdir -p docs

          cat > docs/CLI-Reference.md << 'EOF'
          # CLI Reference

          ## Main Command
          ```
          EOF

          ./target/release/twig --help >> docs/CLI-Reference.md
          echo '```' >> docs/CLI-Reference.md

          # Add each subcommand as a section
          echo "" >> docs/CLI-Reference.md
          echo "## branch" >> docs/CLI-Reference.md
          echo '```' >> docs/CLI-Reference.md
          ./target/release/twig branch --help >> docs/CLI-Reference.md
          echo '```' >> docs/CLI-Reference.md

          echo "" >> docs/CLI-Reference.md
          echo "## cascade" >> docs/CLI-Reference.md
          echo '```' >> docs/CLI-Reference.md
          ./target/release/twig cascade --help >> docs/CLI-Reference.md
          echo '```' >> docs/CLI-Reference.md

          echo "" >> docs/CLI-Reference.md
          echo "## completion" >> docs/CLI-Reference.md
          echo '```' >> docs/CLI-Reference.md
          ./target/release/twig completion --help >> docs/CLI-Reference.md
          echo '```' >> docs/CLI-Reference.md

          echo "" >> docs/CLI-Reference.md
          echo "## creds" >> docs/CLI-Reference.md
          echo '```' >> docs/CLI-Reference.md
          ./target/release/twig creds --help >> docs/CLI-Reference.md
          echo '```' >> docs/CLI-Reference.md

          echo "" >> docs/CLI-Reference.md
          echo "## dashboard" >> docs/CLI-Reference.md
          echo '```' >> docs/CLI-Reference.md
          ./target/release/twig dashboard --help >> docs/CLI-Reference.md
          echo '```' >> docs/CLI-Reference.md

          echo "" >> docs/CLI-Reference.md
          echo "## git" >> docs/CLI-Reference.md
          echo '```' >> docs/CLI-Reference.md
          ./target/release/twig git --help >> docs/CLI-Reference.md
          echo '```' >> docs/CLI-Reference.md

          echo "" >> docs/CLI-Reference.md
          echo "## github" >> docs/CLI-Reference.md
          echo '```' >> docs/CLI-Reference.md
          ./target/release/twig github --help >> docs/CLI-Reference.md
          echo '```' >> docs/CLI-Reference.md

          echo "" >> docs/CLI-Reference.md
          echo "## jira" >> docs/CLI-Reference.md
          echo '```' >> docs/CLI-Reference.md
          ./target/release/twig jira --help >> docs/CLI-Reference.md
          echo '```' >> docs/CLI-Reference.md

          echo "" >> docs/CLI-Reference.md
          echo "## rebase" >> docs/CLI-Reference.md
          echo '```' >> docs/CLI-Reference.md
          ./target/release/twig rebase --help >> docs/CLI-Reference.md
          echo '```' >> docs/CLI-Reference.md

          echo "" >> docs/CLI-Reference.md
          echo "## switch" >> docs/CLI-Reference.md
          echo '```' >> docs/CLI-Reference.md
          ./target/release/twig switch --help >> docs/CLI-Reference.md
          echo '```' >> docs/CLI-Reference.md

          echo "" >> docs/CLI-Reference.md
          echo "## sync" >> docs/CLI-Reference.md
          echo '```' >> docs/CLI-Reference.md
          ./target/release/twig sync --help >> docs/CLI-Reference.md
          echo '```' >> docs/CLI-Reference.md

          echo "" >> docs/CLI-Reference.md
          echo "## tree" >> docs/CLI-Reference.md
          echo '```' >> docs/CLI-Reference.md
          ./target/release/twig tree --help >> docs/CLI-Reference.md
          echo '```' >> docs/CLI-Reference.md

          echo "" >> docs/CLI-Reference.md
          echo "## worktree" >> docs/CLI-Reference.md
          echo '```' >> docs/CLI-Reference.md
          ./target/release/twig worktree --help >> docs/CLI-Reference.md
          echo '```' >> docs/CLI-Reference.md

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit documentation
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/
          git commit -m "docs: auto-update documentation [skip ci]"
          git push

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: twig-docs
          path: docs/
